# C:\Users\user\Desktop\0703flutter_v2\pubspec.yaml

name: t0703
description: "A new Flutter project."
publish_to: 'none' # 프로젝트를 pub.dev에 게시하지 않음을 의미합니다.

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # Flutter SDK 3.8.1 이상 4.0.0 미만 버전에서 호환됩니다.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # iOS 스타일 아이콘 패키지
  go_router: ^13.0.1 # ✅ GoRouter 패키지 (라우팅 관리)
  provider: ^6.1.2 # ✅ MVVM 패턴에서 ViewModel 바인딩을 위한 Provider 패키지
  http: ^0.13.6 # ✅ HTTP 요청을 위한 패키지 (서버 통신)
  image_picker: ^1.1.2 # ✅ 이미지/영상 선택 및 촬영을 위한 패키지 (진단 기능에 필요)
  path_provider: ^2.1.3 # ✅ 파일 시스템 경로 접근을 위한 패키지 (이미지 저장 등에 필요)
  intl: ^0.19.0 # ✅ 날짜 및 시간 포맷팅, 국제화를 위한 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # ✅ 코드 품질 유지를 위한 린트 규칙 패키지

flutter:
  uses-material-design: true # ✅ Material Design 사용을 활성화합니다.
